#!/bin/bash
echo "Content-Type: application/json"
echo "Access-Control-Allow-Origin: *"
echo

if [ "$REQUEST_METHOD" = "POST" ]; then
    if [ "$CONTENT_LENGTH" -gt 0 ]; then
        #LC_ALL=C IFS= read -r -N $CONTENT_LENGTH POST_DATA <&0
        #echo "$POST_DATA" > /usr/lib/cgi-bin/config.json
	cat > /usr/lib/cgi-bin/config.json
    fi
fi
cat /usr/lib/cgi-bin/config.json
