#!/bin/bash
echo "Content-Type: text/plain"
echo "Access-Control-Allow-Origin: *"
echo
echo "'$QUERY_STRING'"
SIFS=$IFS
IFS=/
DATA=($QUERY_STRING)
IFS=$SIFS
echo "'${DATA[0]} ${DATA[1]} ${DATA[2]}'"
sudo nft delete rule ${DATA[0]} ${DATA[1]} handle ${DATA[2]}

sudo nft list ruleset | grep -v tun > /etc/nftables.conf
