#!/bin/bash
echo "Content-Type: text/plain"
echo "Access-Control-Allow-Origin: *"
echo

sudo ln -sf /etc/unbound/blocks/$1 /etc/unbound/unbound-block.conf.d/$1
if [ "$2" == "" ]; then
    sudo systemctl restart unbound
fi
